add job that compares locks

diff --git a/.github/workflows/generate_package_locks.yml b/.github/workflows/generate_package_locks.yml
--- a/.github/workflows/generate_package_locks.yml
+++ b/.github/workflows/generate_package_locks.yml
@@ -8,6 +8,8 @@ on:
 
 jobs:
   generate-package-locks:
+    outputs:
+      package_locks_b64: ${{ steps.generate-package-locks.outputs.package_locks_b64 }}
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
@@ -16,7 +18,7 @@ jobs:
           python-version: "3.10"
       - run: |
           pip install PyYAML
-      - name: Generate lock file JSON from existing directory structure
+      - name: Generate lock file JSON from existing charts
         id: generate-package-locks
         run: |
           set -o pipefail
@@ -30,3 +32,19 @@ jobs:
             || { echo "::error::output package_locks_b64 did not contain base64 content generated from the previous step"; exit 2 ;}
           echo ${{ steps.generate-package-locks.outputs.package_locks_b64 }} | base64 -d | jq \
             || { echo "::error::output package_locks_b64 did not contain valid JSON once decoded" ; exit 3 ;}
+  
+  compare-package-lock-manifests:
+    needs: generate-package-locks
+    runs-on: ubuntu-latest
+    steps:
+      - name: Get production lock file
+        run: |
+          wget https://komish.github.io/actions-workflow-call-test/blob.json -O current-locks.json
+          set -o pipefail
+          test -n "${{ needs.generate-package-locks.outputs.package_locks_b64 }}" \
+            || { echo "::error::output package_locks_b64 did not contain base64 content generated from the previous step"; exit 2 ;}
+          echo ${{ needs.generate-package-locks.outputs.package_locks_b64 }} | base64 -d | jq > generated-locks.json \
+            || { echo "::error::output package_locks_b64 did not contain valid JSON once decoded" ; exit 3 ;}
+          diff -U0 current-locks.json generated-locks.json
+
+        
