add error messaging once sanity check fails

diff --git a/.github/workflows/generate_package_locks.yml b/.github/workflows/generate_package_locks.yml
--- a/.github/workflows/generate_package_locks.yml
+++ b/.github/workflows/generate_package_locks.yml
@@ -7,7 +7,7 @@ on:
   workflow_dispatch:
 
 jobs:
-  build:
+  generate_package_locks:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
@@ -25,5 +25,8 @@ jobs:
           echo "package_locks_b64=$(cat /tmp/packagelocks.json.b64)" >> $GITHUB_OUTPUT
       - name: Decode and display lockfile JSON (Sanity Check)
         run: |
-          test -n "${{ steps.generate-package-locks.outputs.package_locks_b64s }}"
-          echo ${{ steps.generate-package-locks.outputs.package_locks_b64s }} | base64 -d | jq
+          set -o pipefail
+          test -n "${{ steps.generate-package-locks.outputs.package_locks_b64s }}" \
+            || echo "::error:: package_locks_b64 did not contain base64 content generated from the previous step"
+          echo ${{ steps.generate-package-locks.outputs.package_locks_b64s }} | base64 -d | jq \
+            || echo "::error:: package_locks_b64 did not contain valid JSON once decoded"
