fix validations

diff --git a/.github/workflows/generate_package_locks.yml b/.github/workflows/generate_package_locks.yml
--- a/.github/workflows/generate_package_locks.yml
+++ b/.github/workflows/generate_package_locks.yml
@@ -27,6 +27,6 @@ jobs:
         run: |
           set -o pipefail
           test -n "${{ steps.generate-package-locks.outputs.package_locks_b64 }}" \
-            || { echo "::error:: output package_locks_b64 did not contain base64 content generated from the previous step"; exit 2 ;}
-          echo e3t9Cg== | base64 -d | jq \
-            || { echo "::error:: output package_locks_b64 did not contain valid JSON once decoded" ; exit 3 ;}
+            || { echo "::error::output package_locks_b64 did not contain base64 content generated from the previous step"; exit 2 ;}
+          echo ${{ steps.generate-package-locks.outputs.package_locks_b64 }} | base64 -d | jq \
+            || { echo "::error::output package_locks_b64 did not contain valid JSON once decoded" ; exit 3 ;}
